### ISSUE TITLE
virtualenv: cannot access lib: No such virtualenv or site directory

### ISSUE THREAD

**Issue by felipesanches** [graphicore/nametableswapper#4]
Trying to run this locally with

```
dev_appserver.py app/
```

I get this error after clicking "3 - get the fonts"::

```
Traceback (most recent call last):
  File "/home/felipe/devel/prebuilt/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/home/felipe/devel/prebuilt/google-cloud-sdk/platform/google_appengine/google/appengine/api/lib_config.py", line 354, in __getattr__
    self._update_configs()
  File "/home/felipe/devel/prebuilt/google-cloud-sdk/platform/google_appengine/google/appengine/api/lib_config.py", line 290, in _update_configs
    self._registry.initialize()
  File "/home/felipe/devel/prebuilt/google-cloud-sdk/platform/google_appengine/google/appengine/api/lib_config.py", line 165, in initialize
    import_func(self._modname)
  File "/home/felipe/devel/github_felipesanches/nametableswapper/app/appengine_config.py", line 4, in <module>
    vendor.add('lib')
  File "/home/felipe/devel/prebuilt/google-cloud-sdk/platform/google_appengine/google/appengine/ext/vendor/__init__.py", line 44, in add
    'No such virtualenv or site directory' % path)
ValueError: virtualenv: cannot access lib: No such virtualenv or site directory
INFO     2016-10-14 21:55:19,205 module.py:788] default: "POST /changenames HTTP/1.1" 500 -
```

**Comment by felipesanches** [comment]
I created an empty directory called lib/ and now I get a different error:

```
/app/main.py", line 4, in <module>
    from flask import Flask, make_response, request
ImportError: No module named flask
```

And I do have flask installed locally.

**Comment by graphicore** [comment]
I'm using the standard environment: https://cloud.google.com/appengine/docs/python/ if that's of any help. 

I see that I have here locally a diectory at `app/lib` which contains fontTools, flask and the dependencies that come with it. I think the requirements.txt file is so far complete.

I installed the appengine stuff a bit unconventional, the google-cloud-sdk is from some deb package. But that does not contain the python scripts, IMO. so I installed the  google-cloud-sdk python stuff in a venv, as far as I can remember.

See: https://github.com/graphicore/nametableswapper/blob/master/app/appengine_config.py it says `lib` is a "vendor" directory.

Sorry for not adding a readme.

**Comment by graphicore** [comment]
`dev_appserver.py` should be right

**Comment by graphicore** [comment]
I probably used something like: `pip install -t app/lib -r requirements.txt`

**Comment by graphicore** [comment]
And here's related docs: https://cloud.google.com/appengine/docs/python/getting-started/python-standard-env#setting_up_libraries_to_enable_development

**Comment by felipesanches** [comment]
Thanks! It solved the issue!

I've just sent a pull request with a README.
